name: DkpatelInfraPipeline

trigger: none 

pool: todo-pool

stages:

# ---------------- PRE-COMMIT ----------------
- stage: PreCommit
  displayName: Pre-Commit / Static Analysis Stage

  jobs: 
  - job: TerraformValidate
    displayName: Terraform Validate
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip
      displayName: Install unzip

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        backendServiceArm: 'todo-svc'
        backendAzureRmStorageAccountName: 'patelstg'
        backendAzureRmContainerName: 'patelstg'
        backendAzureRmKey: 'tfstate-key'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'

  - job: TerraformFmt
    dependsOn: TerraformValidate
    displayName: Terraform Fmt
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        customCommand: 'fmt'

  - job: tfsec
    dependsOn: TerraformFmt
    displayName: TfSec Scan
    steps:
    - task: tfsec@1
      continueOnError: true
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/'
        additionalArgs: '--soft-fail'

  - job: tflint
    dependsOn: tfsec
    displayName: TFLint
    steps: 
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          winget install TerraformLinters.tflint
          ls
          tflint || exit 0
        errorActionPreference: 'continue'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'

# ---------------- COST ----------------
- stage: costStage
  dependsOn: PreCommit
  displayName: Cost & Impact Assessment Stage
  jobs: 
  - job: InfraCost
    displayName: InfraCost
    steps:
    - script: |
        infracost breakdown --path=.
      displayName: Run Infracost

# ---------------- PLAN ----------------
- stage: plan
  dependsOn: costStage
  displayName: Plan & Review Stage
  jobs: 
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        backendServiceArm: 'todo-svc'
        backendAzureRmStorageAccountName: 'patelstg'
        backendAzureRmContainerName: 'patelcont'
        backendAzureRmKey: 'tfstate_key'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        backendServiceArm: 'todo-svc'

# ---------------- APPROVAL ----------------
- stage: approval
  dependsOn: plan
  displayName: Approval & Governance Stage
  jobs:
  - job: ManualApproval
    displayName: Manual Approval
    pool: server
    steps: 
    - task: ManualValidation@1
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'dkpatel111@outlook.com'
        instructions: 'Please review Terraform plan and approve deployment.'
        onTimeout: 'reject'

# ---------------- APPLY ----------------
- stage: apply
  dependsOn: approval
  displayName: Deploy / Apply Stage
  jobs:
  - job: TerraformApply
    displayName: Terraform Apply
    steps: 
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'todo-svc'
        backendAzureRmStorageAccountName: 'patelstg'
        backendAzureRmContainerName: 'patelcont'
        backendAzureRmKey: 'tfstate_key'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        commandOptions: '-auto-approve'
        backendServiceArm: 'todo-svc'